# Generated by Django 3.2.6 on 2021-08-14 19:11

import cursos.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_arquivo_conteudo_imagem_texto_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudo',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='texto',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.AddField(
            model_name='modulo',
            name='order',
            field=cursos.fields.OrdenarCampos(blank=True, default=0),
            preserve_default=False,
        ),
    ]
